Update staging-deploy.yml

diff --git a/.github/workflows/staging-deploy.yml b/.github/workflows/staging-deploy.yml
--- a/.github/workflows/staging-deploy.yml
+++ b/.github/workflows/staging-deploy.yml
@@ -26,6 +26,10 @@ jobs:
         run: |
           echo "Root directory contents:"
           ls -la
+          echo "Terraform directory contents:"
+          ls -la ./Terraform || echo "Terraform directory not found"
+          echo "Terraform modules contents:"
+          ls -la ./Terraform/modules || echo "Modules directory not found"
           echo "Full repository structure:"
           find . -type f
 
@@ -38,7 +42,9 @@ jobs:
       - name: Terraform Init
         id: init
         run: terraform init -no-color || { echo "Terraform Init failed"; exit 1; }
+        working-directory: ./Terraform
 
       - name: Terraform Plan
         id: plan
         run: terraform plan -input=false -no-color -out tf.plan -detailed-exitcode
+        working-directory: ./Terraform
