Update staging-deploy.yml

diff --git a/.github/workflows/staging-deploy.yml b/.github/workflows/staging-deploy.yml
--- a/.github/workflows/staging-deploy.yml
+++ b/.github/workflows/staging-deploy.yml
@@ -75,8 +75,12 @@ jobs:
         id: plan
         run: |
           echo "Running terraform plan..."
-          erraform plan -input=false -no-color -out=tf.plan || (echo "Terraform plan failed!"; exit 1)
-          
+          terraform plan \
+            -input=false \
+            -no-color \
+            -var-file="terraform.tfvars" \
+            -out=tf.plan || (echo "Terraform plan failed!"; exit 1)
+
           if [ ! -f tf.plan ]; then
             echo "Plan file does not exist!"
             exit 1
